/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const ftml_setup: (a: any, b: any, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => number;
export const render_document: (a: any, b: any, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const render_fragment: (a: any, b: any, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const __wbg_ftmlmounthandle_free: (a: number, b: number) => void;
export const ftmlmounthandle_unmount: (a: number) => [number, number];
export const set_debug_log: () => void;
export const set_server_url: (a: number, b: number) => void;
export const __wbg_leptoscontext_free: (a: number, b: number) => void;
export const leptoscontext_cleanup: (a: number) => [number, number];
export const leptoscontext_wasm_clone: (a: number) => number;
export const get_server_url: () => [number, number];
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_solutions_free: (a: number, b: number) => void;
export const solutions_from_jstring: (a: number, b: number) => number;
export const solutions_to_jstring: (a: number) => [number, number];
export const solutions_check_response: (a: number, b: any) => number;
export const __wbg_exercisefeedback_free: (a: number, b: number) => void;
export const __wbg_get_exercisefeedback_correct: (a: number) => number;
export const __wbg_set_exercisefeedback_correct: (a: number, b: number) => void;
export const __wbg_get_exercisefeedback_score_fraction: (a: number) => number;
export const __wbg_set_exercisefeedback_score_fraction: (a: number, b: number) => void;
export const exercisefeedback_from_jstring: (a: number, b: number) => number;
export const exercisefeedback_to_jstring: (a: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure636_externref_shim: (a: number, b: number, c: any) => void;
export const closure4863_externref_shim: (a: number, b: number, c: any) => number;
export const closure5171_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc09b039c178171a5: (a: number, b: number) => void;
export const closure5197_externref_shim: (a: number, b: number, c: any) => void;
export const closure5241_externref_shim: (a: number, b: number, c: any) => void;
export const closure5599_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
