/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const set_server_url: (a: number, b: number) => void;
export const get_document_html: (a: number, b: number) => any;
export const get_paragraph_html: (a: number, b: number) => any;
export const set_debug_log: () => void;
export const render_document: (a: any, b: any, c: number, d: number, e: number) => [number, number, number];
export const render_fragment_with_cont: (a: any, b: any, c: number, d: any) => [number, number, number];
export const render_fragment: (a: any, b: any, c: number, d: number) => [number, number, number];
export const ftml_setup: (a: any, b: any) => number;
export const __wbg_ftmlmounthandle_free: (a: number, b: number) => void;
export const ftmlmounthandle_unmount: (a: number) => void;
export const get_server_url: () => [number, number];
export const __wbg_leptoscontext_free: (a: number, b: number) => void;
export const leptoscontext_cleanup: (a: number) => void;
export const leptoscontext_wasm_clone: (a: number) => number;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_solutions_free: (a: number, b: number) => void;
export const solutions_from_json: (a: number, b: number) => number;
export const solutions_to_json: (a: number) => [number, number];
export const solutions_check_response: (a: number, b: any) => number;
export const __wbg_exercisefeedback_free: (a: number, b: number) => void;
export const __wbg_get_exercisefeedback_correct: (a: number) => number;
export const __wbg_set_exercisefeedback_correct: (a: number, b: number) => void;
export const exercisefeedback_from_json: (a: number, b: number) => number;
export const exercisefeedback_to_json: (a: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure4313_externref_shim: (a: number, b: number, c: any) => void;
export const closure5489_externref_shim: (a: number, b: number, c: any) => number;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5934a135a905067f: (a: number, b: number) => void;
export const closure5967_externref_shim: (a: number, b: number, c: any) => void;
export const closure5985_externref_shim: (a: number, b: number, c: any) => void;
export const closure6039_externref_shim: (a: number, b: number, c: any) => void;
export const closure6681_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
